#!/bin/bash
-rwxr--r-- 1 root root 61 Oct  7 19:39 0-current_working_directory
-rwxr--r-- 1 root root 50 Oct  7 20:28 1-listit
-rwxr--r-- 1 root root 17 Oct  7 20:48 2-bring_me_home
-rw-r--r-- 1 root root 24 Oct  7 19:14 README.md

